# -*- coding: utf-8 -*-
"""test_neo4j_auradb_v1 (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSfhn_jBYEs0KaGWpArUP3uRK4A-nk5n
"""

# Load libraries
from neo4j import GraphDatabase
import pandas as pd
import os  # Useful for managing environment variables

# Neo4j AURADB Credentials
# URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
URI = "bolt://127.0.0.1:7687"
USER = "neo4j"
PASSWORD = "1234567890"
AUTH = (USER, PASSWORD)

# Create the driver instance
# The driver is responsible for managing connections to the database.

# with GraphDatabase.driver(URI, auth=AUTH) as driver:
#    driver.verify_connectivity()

driver = GraphDatabase.driver(URI, auth=(USER, PASSWORD))

# Verify connection
try:
    driver.verify_connectivity()
    print("✅ Connection to Neo4j AuraDB successful!")
except Exception as e:
    print(f"❌ Connection failed: {e}")

# Cargar CSV
df = pd.read_csv("../raw/nuevo_clean.csv")


df[df["track_name"].isna() | df["artist_name"].isna()]

df.isna().sum()

df = df.dropna()

df.isna().sum()


def insert_music_row(tx, row):
    track = row["track_name"]
    artist = row["artist_name"]
    genres = row["artist_genres"]

    if isinstance(genres, str):
        genres = [g.strip() for g in genres.split(",")]
    else:
        genres = []

    tx.run(
        """
    MERGE (song:Interest {name: $track})
      ON CREATE SET song.type = "song",
                    song.description = "Canción del dataset"

    MERGE (artist:Interest {name: $artist})
      ON CREATE SET artist.type = "artist",
                    artist.description = "Artista del dataset"

    MERGE (cat:Category {name: "Music"})
      ON CREATE SET cat.description = "Todo lo relacionado con música"

    WITH song, artist, cat
    MERGE (song)-[:BELONGS_TO]->(cat)
    MERGE (artist)-[:BELONGS_TO]->(cat)
    MERGE (artist)-[:HAS_SUBINTEREST]->(song)
    """,
        track=track,
        artist=artist,
    )

    for g in genres:
        tx.run(
            """
        MERGE (genre:Genre {name: $genre})
          ON CREATE SET genre.description = "Género musical importado"

        WITH genre
        MATCH (artist:Interest {name: $artist})
        MERGE (artist)-[:HAS_GENRE]->(genre)
        """,
            genre=g,
            artist=artist,
        )


with driver.session() as session:
    for _, row in df.head(2500).iterrows():
        session.execute_write(insert_music_row, row)

driver.close()

print("Importación completada.")

# import random


# driver = GraphDatabase.driver(URI, auth=(USER, PASSWORD))


# def get_existing_interests(tx):
#     result = tx.run("MATCH (i:Interest) RETURN i.name AS name")
#     return [record["name"] for record in result]


# def create_user_with_interests(tx, user_data, interests):
#     query = """
#     CREATE (u:User {
#         id: $id,
#         name: $name,
#         edad: $edad,
#         correo: $correo,
#         usuario: $usuario,
#         hash_contraseña: $hash_contraseña,
#         avatar: $avatar
#     })
#     WITH u
#     UNWIND $interests AS intName
#         MATCH (i:Interest {name: intName})
#         MERGE (u)-[:HAS_INTEREST]->(i)
#     RETURN u
#     """
#     tx.run(query, **user_data, interests=interests)


# def generar_users(n=10):
#     with driver.session() as session:
#         # 1) obtener intereses de la base
#         all_interests = session.execute_read(get_existing_interests)

#         print(f"Intereses encontrados en Neo4j: {len(all_interests)}")

#         for i in range(1, n + 1):
#             user_data = {
#                 "id": i,
#                 "name": f"User{i}",
#                 "edad": random.randint(18, 60),
#                 "correo": f"user{i}@mail.com",
#                 "usuario": f"user{i}",
#                 "hash_contraseña": f"hash_user{i}",
#                 "avatar": f"url_avatar_user{i}",
#             }

#             # Escoger entre 1 y 4 intereses ya existentes
#             k = random.randint(6, min(30, len(all_interests)))
#             user_interests = random.sample(all_interests, k)

#             session.execute_write(create_user_with_interests, user_data, user_interests)

#         print(f"\nUsuarios creados: {n}")


# # -----------------------------------------

# generar_users(50)

# driver.close()
